#!/usr/bin/env python3
"""Emit map_renderer/web/css/tokens.css from config/design_tokens.json.

Idempotent: re-running with unchanged tokens produces byte-identical output.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from tools.tokens import load_tokens  # noqa: E402

_OUT = _ROOT / "map_renderer" / "web" / "css" / "tokens.css"


def _css_var_name(*parts: str) -> str:
    return "--" + "-".join(parts)


def generate_css(tokens: dict | None = None) -> str:
    tok = tokens if tokens is not None else load_tokens()
    lines: list[str] = [
        "/* AUTO-GENERATED by tools/gen_tokens_css.py — do not edit by hand. */",
        ":root {",
    ]

    palette = tok["palette"]
    lines.append(f"  {_css_var_name('palette', 'background')}: {palette['background']};")
    lines.append(f"  {_css_var_name('palette', 'surface')}: {palette['surface']};")
    lines.append(f"  {_css_var_name('text', 'primary')}: {palette['text']['primary']};")
    lines.append(f"  {_css_var_name('text', 'secondary')}: {palette['text']['secondary']};")

    for role, shades in palette["roles"].items():
        for shade in ("core", "glow", "dim"):
            lines.append(
                f"  {_css_var_name('role', role, shade)}: {shades[shade]};"
            )

    typo = tok["typography"]
    for key in ("display", "primary", "mono", "math"):
        lines.append(f"  {_css_var_name('font', key)}: '{typo[key]}';")

    for fmt, sizes in typo["scale"].items():
        for role, px in sizes.items():
            lines.append(
                f"  {_css_var_name('font-size', fmt, role)}: {px}px;"
            )

    glow = tok["glow"]
    lines.append(f"  {_css_var_name('glow', 'core-px')}: {glow['core_px']}px;")
    lines.append(f"  {_css_var_name('glow', 'halo-px')}: {glow['halo_px']}px;")
    lines.append(f"  {_css_var_name('glow', 'halo-opacity')}: {glow['halo_opacity']};")

    timing = tok["timing"]
    for key, value in timing.items():
        css_key = key.replace("_", "-")
        unit = "ms" if key.endswith("_ms") else ("s" if key.endswith("_s") else "")
        suffix = f" {unit}" if unit else ""
        lines.append(f"  {_css_var_name('timing', css_key)}: {value}{suffix};")

    grading = tok["grading"]
    lines.append(
        f"  {_css_var_name('grading', 'vignette-opacity')}: {grading['vignette_opacity']};"
    )
    lines.append(
        f"  {_css_var_name('grading', 'grain-opacity')}: {grading['grain_opacity']};"
    )

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    css = generate_css()
    _OUT.parent.mkdir(parents=True, exist_ok=True)
    _OUT.write_text(css, encoding="utf-8")
    print(_OUT)


if __name__ == "__main__":
    main()
